### PR TITLE
Fix size verification

### LINKED ISSUE #32: [BUG] New ZIM is deleted even though downloaded and checksum succeded
When using the verify library flag (-f) and the size verification of a ZIM fails, the lock file of the new ZIM is not deleted causing the new ZIM to be deleted even though the download succeed and checksum passed.
Animation

### PR DESCRIPTION
**Pull request by jojo2357**
Fix #32

### CODE REVIEW

**Comment by jojo2357** [comment]
@DocDrydenn I have done something to deprecate `kiwix-zim` in favor of the name `kiwix-zim-updater` you will now get a warning as well as an exit code of `2` upon successful completion but having called `kiwix-zim` hopefully those running cron will notice and change their configs? What do you think?

**Comment by DocDrydenn** [comment]
Sounds good to me. I'll give it a go today. The warning is good. Might wat to add a note on the main Readme... for those who may be running it as a cron and won't see the warning.

**Comment by jojo2357** [comment]
The readme is changed in this pr

**Comment by Jaifroid** [comment]
Looks like a good approach to me too!

**Comment by jojo2357** [comment]
I will merge around 00:00Z

**Review by Jaifroid — APPROVED** [review]
All looks good to me in overview (but I haven't tested the deprecation code).

**Comment by jojo2357** [comment]
If we messed up terribly, then we will find out soon enough!

**Pull request merged**
